import { Inter ,Chakra_Petch, Prompt } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const chakra_Petch = Chakra_Petch({
  variable: "--font-Chakra-Petch",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "700"],
});


export const metadata = {
  title: "Tawawan Dog Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
      <title>Tawawan Dog Cafe</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" type="image/x-icon" />
    </>
      <body
        className={`${inter.variable}${chakra_Petch.variable}${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
