import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

if (typeof window === "undefined") {
  import("../lib/clearOrdersScheduler.js");
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tawawan Dog Cafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
      <title>Tawawan Dog Cafe</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" type="image/x-icon" />
    </>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
